### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stoeckel4code** [VACILT/student_project#3]
### Roadmap

- [x] create roadmap
- [x] clean code
- [x] using of additional variables
- [x] add ROI-function [here](https://holoviews.org/gallery/demos/bokeh/box_draw_roi_editor.html)
- [x] standardize coeffizents
- [x] tap-plot
- [x] get a look at [Awesome Panel](https://awesome-panel.org/app)
- [x] get a look at [Gridspec](https://panel.holoviz.org/reference/layouts/GridSpec.html#layouts-gallery-gridspec)
- [x] presentation
